### ISSUE TITLE
List on Graylog Marketplace

### ISSUE THREAD

**Issue by lennartkoopmann** [yeebase/Yeebase.Graylog2#1]
We have launched the beta of the Graylog Marketplace: https://marketplace.graylog.org/

The Marketplace is the central directory of all Graylog add-ons and integrations, including GELF libraries.

You would help us a lot if you could submit your GELF library there. :)

**Comment by brgmn** [comment]
This package is deprecated. I submitted the new package to the Graylog marketplace instead https://github.com/yeebase/Yeebase.Graylog
